apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: training-web
  namespace: s12
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx

  rules:
  - host: s12.pmwi.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: training-web
            port:
              number: 80

